[package]
name = "lp-server"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]

[dependencies]
juniper = "0.9.2"
juniper_rocket = "0.1.2"
lazy_static = "1.0.0"
lp = { path = "../lp" }
rocket = "0.3.6"
rocket_codegen = "0.3.6"
