[package]
name = "lp-server"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
edition = "2018"

[dependencies]
juniper = "0.12.0"
juniper_warp = "0.3.0"
lp = { path = "../lp" }
warp = "0.1.13"
