[package]
name = "lp-tag"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
build = "build.rs"

[dependencies]
glob = "0.2.11"
lazy_static = "0.2.2"
libc = "0.2.21"
regex = "0.2.0"
reqwest = "0.4.0"
serde = "0.9.11"
serde_derive = "0.9.11"
serde_json = "0.9.9"
unidecode = "0.3.0"

[build-dependencies]
gcc = "0.3.45"
